#!/usr/bin/env bash
#
# Regenerate NOTICE and THIRD_PARTY_LICENSES.md from the current Cargo.lock
# (#1488). Lists every third-party crate in the workspace's *distributed*
# dependency graph (normal + build deps, dev-deps excluded) with its license,
# via `cargo license`.
#
# These files are GENERATED — do not hand-edit. Run this after any dependency
# change. CI verifies they are current (see .github/workflows/ci.yml,
# `license-inventory` job) and fails if they drift from Cargo.lock.
#
# Output is deterministic (sorted, no timestamps) so `git diff --exit-code`
# is a reliable staleness check.
#
set -euo pipefail

# Byte-stable, locale-independent sorting so the generated files are identical
# on every host (CI Linux vs. a dev macOS box). cargo-license lists all-platform
# deps by default (no --filter-platform), which is also host-independent.
export LC_ALL=C

cd "$(dirname "$0")/.."

if ! command -v cargo-license >/dev/null 2>&1; then
  echo "error: cargo-license not installed. Install the version CI pins:" >&2
  echo "  cargo install cargo-license --version 0.7.0 --locked" >&2
  exit 1
fi

# name<TAB>version<TAB>license for every third-party crate, excluding our own
# workspace crates. --avoid-dev-deps: dev/test/bench-only deps are not part of
# the distributed artifacts. cargo-license --tsv columns are:
#   1=name 2=version 3=authors 4=repository 5=license 6=license_file 7=description
# Sorted + de-duped for deterministic output.
rows=$(cargo license --all-features --avoid-dev-deps --tsv \
  | tail -n +2 \
  | awk -F'\t' 'BEGIN{OFS="\t"}
      $1 !~ /^conductor(-core|-daemon|-capture)?$/ {print $1, $2, $5}' \
  | sort -u)

count=$(printf '%s\n' "$rows" | grep -c . || true)

# ---- THIRD_PARTY_LICENSES.md ------------------------------------------------
{
  echo "# Third-Party Licenses"
  echo
  echo "<!-- GENERATED FILE — do not edit by hand."
  echo "     Regenerate: scripts/gen-third-party-licenses.sh"
  echo "     CI fails if this drifts from Cargo.lock (#1488). -->"
  echo
  echo "Conductor distributes the third-party Rust crates listed below, taken"
  echo "from the workspace dependency graph (\`cargo license --all-features"
  echo "--avoid-dev-deps\`). Dev/test-only dependencies are excluded. All listed"
  echo "licenses are OSI-approved and compatible with Conductor's MIT license."
  echo
  echo "Total third-party crates: ${count}"
  echo
  echo "## License summary"
  echo
  printf '%s\n' "$rows" \
    | awk -F'\t' '{c[$3]++} END{for (l in c) printf "- %s: %d\n", l, c[l]}' \
    | sort
  echo
  echo "## Dependencies"
  echo
  echo "| Crate | Version | License |"
  echo "|-------|---------|---------|"
  printf '%s\n' "$rows" \
    | awk -F'\t' '{printf "| %s | %s | %s |\n", $1, $2, $3}'
  echo
  echo "## Full license texts"
  echo
  echo "This file lists license *identifiers*. For the complete license text of"
  echo "each crate, run \`cargo license --all-features --avoid-dev-deps\` locally"
  echo "(the same inputs used to generate this list), or visit the crate on"
  echo "<https://crates.io> / its source repository."
  echo
  echo "## Regeneration"
  echo
  echo "Generated from Cargo.lock by \`scripts/gen-third-party-licenses.sh\`."
  echo "Re-run it after any dependency change; CI fails if this file is stale."
} > THIRD_PARTY_LICENSES.md

# ---- NOTICE -----------------------------------------------------------------
{
  echo "Conductor"
  echo "Copyright 2025-2026 Monstrous Media"
  echo
  echo "This product includes software developed by the Rust community. It"
  echo "distributes ${count} third-party Rust crates; see THIRD_PARTY_LICENSES.md"
  echo "for the complete per-crate list and licenses."
  echo
  echo "License summary:"
  printf '%s\n' "$rows" \
    | awk -F'\t' '{c[$3]++} END{for (l in c) printf "- %s: %d\n", l, c[l]}' \
    | sort
  echo
  echo "All dependencies use OSI-approved licenses compatible with MIT."
  echo
  echo "This NOTICE is generated by scripts/gen-third-party-licenses.sh; do not"
  echo "edit the dependency summary by hand."
  echo
  echo "Trademark Notice:"
  echo "Native Instruments, Maschine, and Maschine Mikro are trademarks of Native"
  echo "Instruments GmbH. Conductor is an independent open source project and is not"
  echo "affiliated with, endorsed by, or sponsored by Native Instruments GmbH."
} > NOTICE

echo "wrote THIRD_PARTY_LICENSES.md and NOTICE (${count} third-party crates)"
